services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semantic_search
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data